/** Renders a JSON-LD structured-data script tag. */
export default function JsonLd({ data }: { data: object | object[] }) {
  return (
    <script
      type="application/ld+json"
      // JSON-LD content is generated by us from trusted CMS data.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
